[project]
name = "stablefilter"
version = "0.1.0"
description = "稳定扩散模型标签智能分类工具"
authors = [
    { name = "X-Zero-L", email = "zeroeeau@gmail.com" }
]
dependencies = [
    "dotenv>=0.9.9",
    "openai>=1.68.2",
    "pydantic-ai>=0.0.43",
    "pydantic-settings>=2.8.1",
]
requires-python = ">=3.10"
